# Generated by Django 2.1.5 on 2019-01-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dp',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
